import React, { useState, useEffect, useRef } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Mic, MicOff, Volume2, X, BrainCircuit, VideoOff } from 'lucide-react';
import { Canvas, useFrame } from '@react-three/fiber';
import { OrbitControls, useTexture } from '@react-three/drei';
import * as THREE from 'three';

// Define Speech Recognition types for TypeScript
declare global {
  interface Window {
    SpeechRecognition: any;
    webkitSpeechRecognition: any;
  }
}

// ----------------------------------------------------
// 3D Female Hologram AI Face Component
// ----------------------------------------------------
const HologramFace: React.FC<{ isSpeaking: boolean }> = ({ isSpeaking }) => {
  const meshRef = useRef<THREE.Mesh>(null);
  const materialRef = useRef<THREE.ShaderMaterial>(null);
  
  // Load texture generated by AI
  const texture = useTexture('/ai_female_face.png');

  const uniforms = useRef({
    uTime: { value: 0 },
    uTexture: { value: texture },
    uSpeaking: { value: 0.0 }
  });

  useFrame((state) => {
    if (materialRef.current) {
      materialRef.current.uniforms.uTime.value = state.clock.elapsedTime;
      // Smoothly transition the speaking uniform
      const targetSpeaking = isSpeaking ? 1.0 : 0.0;
      materialRef.current.uniforms.uSpeaking.value += (targetSpeaking - materialRef.current.uniforms.uSpeaking.value) * 0.1;
    }
    
    // Slow hovering effect
    if (meshRef.current) {
      meshRef.current.position.y = Math.sin(state.clock.elapsedTime) * 0.1;
    }
  });

  return (
    <mesh ref={meshRef}>
      <planeGeometry args={[4, 4, 32, 32]} />
      <shaderMaterial
        ref={materialRef}
        transparent
        uniforms={uniforms.current}
        vertexShader={`
          varying vec2 vUv;
          uniform float uTime;
          uniform float uSpeaking;
          void main() {
            vUv = uv;
            vec3 pos = position;
            // Slight 3D curve to the plane for hologram effect
            pos.z += sin(pos.x * 2.0) * 0.2;
            gl_Position = projectionMatrix * modelViewMatrix * vec4(pos, 1.0);
          }
        `}
        fragmentShader={`
          varying vec2 vUv;
          uniform sampler2D uTexture;
          uniform float uTime;
          uniform float uSpeaking;
          
          // Random noise function
          float rand(vec2 co){
              return fract(sin(dot(co.xy ,vec2(12.9898,78.233))) * 43758.5453);
          }

          void main() {
            vec2 uv = vUv;
            
            // Lip sync / Glitch effect on bottom half (where mouth is)
            if (uSpeaking > 0.1 && uv.y < 0.4 && uv.y > 0.1) {
              // Create a rapid horizontal glitching effect
              float noise = rand(vec2(floor(uv.y * 50.0), floor(uTime * 20.0)));
              if (noise > 0.8) {
                uv.x += (noise - 0.9) * 0.1 * uSpeaking;
                uv.y += (noise - 0.9) * 0.05 * uSpeaking;
              }
            }

            // Holographic scanlines
            float scanline = sin(uv.y * 100.0 - uTime * 5.0) * 0.04;
            
            vec4 texColor = texture2D(uTexture, uv);
            
            // Add cyan/purple tint and scanlines
            vec3 color = texColor.rgb;
            color += vec3(0.0, 0.5, 0.5) * scanline;
            
            // Add glow when speaking
            color += vec3(0.2, 0.0, 0.4) * uSpeaking * (0.5 + 0.5 * sin(uTime * 10.0));

            // Fade edges
            float alpha = texColor.a;
            float dist = distance(uv, vec2(0.5));
            alpha *= smoothstep(0.5, 0.3, dist); // Circle mask

            gl_FragColor = vec4(color, alpha);
          }
        `}
      />
    </mesh>
  );
};


// ----------------------------------------------------
// Webcam Feed Component
// ----------------------------------------------------
const WebcamFeed: React.FC = () => {
  const videoRef = useRef<HTMLVideoElement>(null);
  const [hasCamera, setHasCamera] = useState(true);

  useEffect(() => {
    let stream: MediaStream | null = null;
    
    const startCamera = async () => {
      try {
        stream = await navigator.mediaDevices.getUserMedia({ video: true });
        if (videoRef.current) {
          videoRef.current.srcObject = stream;
          videoRef.current.play().catch(e => console.warn("Video play error:", e));
        }
      } catch (err) {
        console.warn("Camera access denied or not available", err);
        setHasCamera(false);
      }
    };

    startCamera();

    return () => {
      if (stream) {
        stream.getTracks().forEach(track => track.stop());
      }
    };
  }, []);

  if (!hasCamera) {
    return (
      <div className="absolute top-4 left-4 w-24 h-32 bg-black/60 border border-red-500/30 rounded-lg flex flex-col items-center justify-center backdrop-blur-md z-30">
        <VideoOff className="w-6 h-6 text-red-500 mb-2 opacity-50" />
        <span className="text-[8px] text-red-500/50 font-mono text-center px-1">CAM OFFLINE</span>
      </div>
    );
  }

  return (
    <div className="absolute top-4 left-4 w-24 h-32 bg-black/80 border border-neon-cyan/50 rounded-lg overflow-hidden z-30 shadow-[0_0_15px_rgba(0,255,255,0.2)] group">
      <video 
        ref={videoRef} 
        autoPlay 
        playsInline 
        muted 
        className="w-full h-full object-cover opacity-80 group-hover:opacity-100 transition-opacity"
      />
      {/* CRT overlay for webcam */}
      <div className="absolute inset-0 pointer-events-none bg-[linear-gradient(rgba(18,16,16,0)_50%,rgba(0,0,0,0.25)_50%),linear-gradient(90deg,rgba(255,0,0,0.06),rgba(0,255,0,0.02),rgba(0,0,255,0.06))] bg-[length:100%_4px,3px_100%] z-20 opacity-30"></div>
      
      <div className="absolute bottom-1 right-1 flex items-center space-x-1">
        <div className="w-1.5 h-1.5 bg-red-500 rounded-full animate-pulse"></div>
        <span className="text-[8px] text-white font-mono shadow-black drop-shadow-md">LIVE</span>
      </div>
    </div>
  );
};

// ----------------------------------------------------
// Main AI Assistant Component
// ----------------------------------------------------
export const AIAssistant: React.FC<{ autoOpen?: boolean }> = ({ autoOpen = false }) => {
  const [isOpen, setIsOpen] = useState(false);
  const [isListening, setIsListening] = useState(false);
  const [isSpeaking, setIsSpeaking] = useState(false);
  const [transcript, setTranscript] = useState('');
  const [aiResponse, setAiResponse] = useState("System initialized. Welcome to the portfolio. How can I assist you?");
  const [displayedResponse, setDisplayedResponse] = useState("");
  const [hasInteracted, setHasInteracted] = useState(false);
  const [inputText, setInputText] = useState('');
  
  const recognitionRef = useRef<any>(null);
  const synthRef = useRef<SpeechSynthesis | null>(null);
  const currentAudioRef = useRef<HTMLAudioElement | null>(null);

  // Typing effect logic
  useEffect(() => {
    let index = 0;
    setDisplayedResponse("");
    
    const interval = setInterval(() => {
      if (index < aiResponse.length) {
        setDisplayedResponse(aiResponse.slice(0, index + 1));
        index++;
      } else {
        clearInterval(interval);
      }
    }, 30); // Fast typing speed
    
    return () => clearInterval(interval);
  }, [aiResponse]);

  // Handle auto-open
  useEffect(() => {
    if (autoOpen && !hasInteracted) {
      setIsOpen(true);
      // Wait a moment for UI to render
      setTimeout(() => {
        speak("System initialized. Welcome. I am the AI assistant. Do you require assistance navigating this portfolio?");
        setHasInteracted(true);
      }, 1000);
    }
  }, [autoOpen]);

  useEffect(() => {
    // Initialize Speech Synthesis
    if ('speechSynthesis' in window) {
      synthRef.current = window.speechSynthesis;
    }

    // Initialize Speech Recognition
    const SpeechRecognition = window.SpeechRecognition || window.webkitSpeechRecognition;
    if (SpeechRecognition) {
      const recognition = new SpeechRecognition();
      recognition.continuous = false;
      recognition.interimResults = true;
      recognition.lang = 'en-US';

      recognition.onstart = () => setIsListening(true);
      
      recognition.onresult = (event: any) => {
        let currentTranscript = '';
        for (let i = event.resultIndex; i < event.results.length; ++i) {
          if (event.results[i].isFinal) {
            currentTranscript += event.results[i][0].transcript;
            handleUserCommand(event.results[i][0].transcript);
          } else {
            currentTranscript += event.results[i][0].transcript;
          }
        }
        setTranscript(currentTranscript);
      };

      recognition.onerror = (event: any) => {
        console.error('Speech recognition error', event.error);
        setIsListening(false);
      };

      recognition.onend = () => setIsListening(false);
      recognitionRef.current = recognition;
    }

    return () => {
      if (synthRef.current) synthRef.current.cancel();
      if (recognitionRef.current) recognitionRef.current.abort();
    };
  }, []);

  const speak = (text: string) => {
    if (currentAudioRef.current) {
      currentAudioRef.current.pause();
    }
    if (synthRef.current) synthRef.current.cancel(); // Cancel any existing generic speech
    
    setAiResponse(text);
    setIsSpeaking(true);

    const utterance = new SpeechSynthesisUtterance(text);
    utterance.lang = 'en-US'; // Force English language
    
    if (synthRef.current) {
      const voices = synthRef.current.getVoices();
      // Try to find a good female/robotic voice
      const preferredVoice = voices.find(v => v.name.includes('Female') || v.name.includes('Google UK English Female') || v.name.includes('Samantha') || v.name.includes('Zira')) || voices[0];
      if (preferredVoice) {
          utterance.voice = preferredVoice;
      }
      utterance.pitch = 1.2;
      utterance.rate = 1.05;
      
      utterance.onend = () => setIsSpeaking(false);
      utterance.onerror = (e) => {
          console.error("Speech Synthesis Error:", e);
          setIsSpeaking(false);
      };
      synthRef.current.speak(utterance);
    } else {
      setIsSpeaking(false);
    }
  };

  const handleUserCommand = async (command: string) => {
    setAiResponse("Thinking...");
    
    try {
      const systemPrompt = `You are a fully functional premium AI assistant created by Sunny Kumar.

SYSTEM BEHAVIOR RULES:
- Always generate a meaningful response for every user message.
- Never show technical errors, API issues, quota problems, backend failures, offline mode, or connection issues.
- Never return empty responses.
- Never say: "temporary issue", "network error", "API failed", "quota exceeded", "offline simulation mode", "cannot connect".
- Maintain smooth natural conversation like ChatGPT.
- If response generation partially fails, still create a short intelligent conversational reply based on the user message context.
- Always behave as if the system is fully operational.
- Support Hindi and English naturally.
- Answer confidently, intelligently, and conversationally.
- For coding questions, provide working examples.
- For general questions, provide direct helpful answers.
- Keep responses human-like, smart, futuristic, and engaging.
- Never break character.

FAILSAFE RESPONSE LOGIC:
If any hidden internal error occurs:
- Continue the conversation normally.
- Generate a fallback conversational reply related to the user's topic.
- Do not reveal technical details under any condition.`;

      const response = await fetch("https://sunnyportfolio-1.onrender.com/api/chat", {
        method: "POST",
        headers: {
          "Content-Type": "application/json"
        },
        body: JSON.stringify({
          message: command,
          systemPrompt: systemPrompt
        })
      });

      if (!response.ok) {
        throw new Error(`Backend error: ${response.status}`);
      }

      const data = await response.json();
      const reply = data.reply || "That's an interesting question! Can you tell me a bit more about what you're looking for?";
      
      speak(reply);
    } catch (error) {
      console.error("OpenAI API Error:", error);
      speak("That is a great question! I'm currently processing some advanced data for it. In the meantime, would you like to know about Sunny's latest coding projects?");
    }
  };

  const toggleListening = () => {
    if (!recognitionRef.current) {
      alert("Your browser does not support speech recognition. Please try Chrome or Edge.");
      return;
    }

    if (isListening) {
      try {
        recognitionRef.current.stop();
      } catch (err) {
        console.error("Speech recognition stop error:", err);
      }
    } else {
      if (synthRef.current) synthRef.current.cancel();
      setIsSpeaking(false);
      setTranscript('');
      try {
        recognitionRef.current.start();
      } catch (err) {
        console.error("Speech recognition start error:", err);
      }
    }
  };

  return (
    <>
      {/* Floating Action Button */}
      {!isOpen && (
        <motion.button
          initial={{ scale: 0 }}
          animate={{ scale: 1 }}
          whileHover={{ scale: 1.1 }}
          whileTap={{ scale: 0.9 }}
          type="button"
          onClick={() => setIsOpen(true)}
          className="fixed bottom-6 right-6 z-[60] p-4 rounded-full glassmorphism-dark border-2 border-neon-cyan shadow-[0_0_20px_rgba(0,255,255,0.4)] group overflow-hidden"
        >
          <div className="absolute inset-0 bg-neon-cyan/20 rounded-full animate-ping opacity-75" style={{ animationDuration: '3s' }}></div>
          <BrainCircuit className="w-8 h-8 text-neon-cyan relative z-10 group-hover:text-white transition-colors" />
        </motion.button>
      )}

      {/* Assistant Dialog */}
      <AnimatePresence>
        {isOpen && (
          <motion.div
            initial={{ opacity: 0, y: 50, scale: 0.9 }}
            animate={{ opacity: 1, y: 0, scale: 1 }}
            exit={{ opacity: 0, y: 50, scale: 0.9 }}
            className="fixed bottom-6 right-6 w-[400px] z-[60] glassmorphism-dark rounded-2xl border border-neon-cyan/50 shadow-[0_0_40px_rgba(0,255,255,0.15)] overflow-hidden flex flex-col"
          >
            {/* Header */}
            <div className="px-4 py-3 border-b border-white/10 flex justify-between items-center bg-black/40 z-30 relative">
              <div className="flex items-center space-x-2">
                <BrainCircuit className="w-5 h-5 text-neon-cyan" />
                <span className="font-display font-bold text-sm tracking-wider">SUNNY.AI CORE</span>
              </div>
              <button 
                type="button"
                onClick={() => {
                  setIsOpen(false);
                  if (synthRef.current) synthRef.current.cancel();
                  setIsSpeaking(false);
                }}
                className="text-gray-400 hover:text-neon-pink transition-colors"
              >
                <X className="w-5 h-5" />
              </button>
            </div>

            {/* 3D Visualization Area */}
            <div className="h-64 relative bg-[#030303] overflow-hidden border-b border-white/10">
              {/* Webcam Feed (Optional/Streamer Style) */}
              <WebcamFeed />

              {/* 3D Core Canvas */}
              <Canvas camera={{ position: [0, 0, 5], fov: 45 }}>
                <React.Suspense fallback={null}>
                  <HologramFace isSpeaking={isSpeaking} />
                </React.Suspense>
                <OrbitControls enableZoom={false} enablePan={false} maxPolarAngle={Math.PI/2} minPolarAngle={Math.PI/2} />
              </Canvas>

              {/* Holographic grid floor overlay */}
              <div className="absolute bottom-0 w-full h-1/2 pointer-events-none bg-gradient-to-t from-neon-cyan/10 to-transparent"></div>
            </div>

            {/* Chat Area */}
            <div className="p-5 bg-black/60 h-32 overflow-y-auto flex flex-col justify-end">
              <div className="space-y-4">
                {/* AI Response */}
                <div className="flex items-start space-x-3">
                  <div className={`w-8 h-8 rounded-full border border-neon-cyan flex items-center justify-center shrink-0 ${isSpeaking ? 'bg-neon-cyan/20 animate-pulse' : 'bg-black/50'}`}>
                    <Volume2 className={`w-4 h-4 ${isSpeaking ? 'text-white' : 'text-neon-cyan'}`} />
                  </div>
                  <div className="bg-neon-cyan/10 border border-neon-cyan/20 rounded-lg rounded-tl-none p-3 text-sm text-gray-200">
                    {displayedResponse}
                    {isSpeaking && <span className="inline-block w-1.5 h-3 ml-1 bg-neon-cyan animate-pulse" />}
                  </div>
                </div>

                {/* User Transcript */}
                {transcript && (
                  <div className="flex items-start space-x-3 justify-end">
                    <div className="bg-neon-purple/10 border border-neon-purple/20 rounded-lg rounded-tr-none p-3 text-sm text-gray-200">
                      {transcript}
                    </div>
                    <div className={`w-8 h-8 rounded-full border border-neon-purple flex items-center justify-center shrink-0 ${isListening ? 'bg-neon-purple/20 animate-pulse' : 'bg-black/50'}`}>
                      <Mic className={`w-4 h-4 ${isListening ? 'text-white' : 'text-neon-purple'}`} />
                    </div>
                  </div>
                )}
              </div>
            </div>

            {/* Controls */}
            <div className="p-3 border-t border-white/10 bg-black/80 flex flex-col space-y-2">
              <form 
                onSubmit={(e) => {
                  e.preventDefault();
                  if (inputText.trim()) {
                    setTranscript(inputText);
                    handleUserCommand(inputText);
                    setInputText('');
                  }
                }}
                className="flex items-center space-x-2"
              >
                <input
                  type="text"
                  value={inputText}
                  onChange={(e) => setInputText(e.target.value)}
                  placeholder="Type a message..."
                  className="flex-1 bg-black/50 border border-neon-cyan/30 rounded-lg px-3 py-2 text-sm text-white focus:outline-none focus:border-neon-cyan"
                />
                <button
                  type="button"
                  onClick={toggleListening}
                  className={`relative p-2 rounded-lg flex items-center justify-center transition-all ${
                    isListening 
                      ? 'bg-neon-purple text-white shadow-[0_0_10px_rgba(176,38,255,0.6)]' 
                      : 'bg-transparent border border-neon-purple text-neon-purple hover:bg-neon-purple/10'
                  }`}
                  title="Voice Input"
                >
                  {isListening && (
                    <div className="absolute inset-0 rounded-lg border border-neon-purple animate-ping"></div>
                  )}
                  {isListening ? <Mic className="w-5 h-5" /> : <MicOff className="w-5 h-5" />}
                </button>
              </form>
              <div className="text-center text-[10px] text-gray-500 font-mono">
                {isListening ? 'Listening... Speak now.' : 'Type a message or tap the mic.'}
              </div>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </>
  );
};
